language: cpp

compiler:
  - clang
  - gcc
  
env:
  matrix:
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release

install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update 
  - sudo apt-get install libgmp-dev 
  - sudo apt-get install libboost-program-options1.54-dev libboost-iostreams1.54-dev libboost-test1.54-dev libboost-thread1.54-dev libboost-system1.54-dev
  - sudo apt-get install default-jre
  - wget "http://yices.csl.sri.com/cgi-bin/yices2-newnewdownload.cgi?file=yices-2.3.1-src.tar.gz&accept=I+Agree" -O yices.tar.gz
  - tar xzvf yices.tar.gz
  - cd yices* && autoconf && ./configure --prefix=/usr && make MODE=release && sudo make MODE=release install && cd ..
  
script:
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
  - make 
  - make check
