language: cpp

matrix:
  - CMAKE_BUILD_TYPE=Debug
  - CMAKE_BUILD_TYPE=Release

install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update 
  - sudo apt-get install g++ 
  - sudo apt-get install libgmp-dev 
  - sudo apt-get install libboost-program-options1.54-dev libboost-iostreams1.54-dev libboost-test1.54-dev 
  - sudo apt-get install default-jre

script:
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ..
  - make 
